/*                        HOMEWORK                 */

-- INTERMEDIATE PROBLEMS

USE `AWESOME CHOCOLATES`; -- MAKE THE DATABASE DEFAULT

-- 1. Print details of shipments (sales) where amounts are > 2,000 and boxes are <100?
SELECT * FROM SALES
WHERE AMOUNT  > 2000 AND BOXES < 100;

-- 2. How many shipments (sales) each of the sales persons had in the month of January 2022?
SELECT P.SALESPERSON, COUNT(*) AS SHIPMENT
FROM SALES S
JOIN PEOPLE P ON S.SPID = P.SPID
WHERE SALEDATE BETWEEN '2022-1-1' AND '2022-1-31'
GROUP BY SALESPERSON;

-- 3. Which product sells more boxes? Milk Bars or Eclairs?
SELECT PRODUCT, SUM(BOXES) AS NO_OF_BOXES
FROM SALES S
JOIN PRODUCTS P ON S.PID = P.PID
WHERE PRODUCT IN ('MILK BARS','ECLAIRS')
GROUP BY PRODUCT 
ORDER BY /*SUM(BOXES)*/ NO_OF_BOXES DESC;
# MILK BARS = 130995 AND ECLAIRS = 144651 SO ECLAIRS SELLS MORE BOXES

-- 4. Which product sold more boxes in the first 7 days of February 2022? Milk Bars or Eclairs?
SELECT PRODUCT, SUM(BOXES) AS NO_OF_BOXES
FROM SALES S
JOIN PRODUCTS P ON S.PID = P.PID
WHERE PRODUCT IN ('Milk Bars','Eclairs') 
	AND (SALEDATE BETWEEN '2022-02-01' AND '2022-02-07')
GROUP BY PRODUCT; 
  # MILK BARS = 818 AND ECLAIRS = 1019 SO ECLAIRS SELLS MORE BOXES IN THOSE SEVEN DAYS
  
/*select pr.product, sum(boxes) as Total_Boxes
from sales s
join products pr on s.pid = pr.pid
where pr.Product in ('Milk Bars', 'Eclairs')
and s.saledate between '2022-2-1' and '2022-2-7'
group by pr.product; */
  
-- 5. Which shipments had under 100 customers & under 100 boxes? Did any of them occur on Wednesday?
SELECT *
FROM SALES
WHERE CUSTOMERS < 100 AND BOXES < 100;

#SHIPMENT OCCUR ON WEDNESDAY
SELECT *,
CASE
    WHEN WEEKDAY(SALEDATE)=2 THEN 'WEDNESDAY SHIPMENT'
    ELSE ''
END AS 'W SHIPMENT'
FROM SALES
WHERE CUSTOMERS < 100 AND BOXES < 100;

-- HARD PROBLEMS

/* 1. What are the names of salespersons who had at least one shipment (sale) 
in the first 7 days of January 2022? */
SELECT DISTINCT(SALESPERSON)
FROM SALES S
JOIN PEOPLE P ON S.SPID = P.SPID
WHERE SALEDATE BETWEEN '2022-01-01' AND '2022-01-07';

/* MY SOLLUTION */
SELECT DISTINCT(P.SALESPERSON)
FROM SALES S
JOIN PEOPLE P ON S.SPID = P.SPID
WHERE S.BOXES > 1 AND SALEDATE BETWEEN '2022-01-01' AND '2022-01-07'; 

SELECT COUNT(DISTINCT(SALESPERSON)) # 25
FROM SALES S
JOIN PEOPLE P ON S.SPID = P.SPID
WHERE SALEDATE BETWEEN '2022-01-01' AND '2022-01-07';

-- 2. Which salespersons did not make any shipments in the first 7 days of January 2022?
SELECT P.SALESPERSON
FROM PEOPLE P
WHERE P.SPID NOT IN
(SELECT DISTINCT(S.SPID) 
FROM SALES S
WHERE S.SALEDATE BETWEEN  '2022-01-01' AND '2022-01-07');

-- MY SOLLUTION
SELECT P.SALESPERSON 
FROM PEOPLE P
LEFT JOIN SALES S ON P.SPID = S.SPID AND S.SALEDATE BETWEEN  '2022-01-01' AND '2022-01-07'
WHERE S.SPID IS NULL;

-- 3. How many times we shipped more than 1,000 boxes in each month? MY SOLLUTION
SELECT DATE_FORMAT(SALEDATE,'%Y-%m') AS MONTH, COUNT(*) AS NO_OF_BOXES_SHIPPED
FROM SALES
WHERE BOXES > 1000
GROUP BY DATE_FORMAT(SALEDATE,'%Y-%m') # DATE WILL EXTRACT LIKE THIS 2022-03.......
ORDER BY MONTH DESC;

SELECT DATE_FORMAT(SALEDATE,'%Y-%M') AS MONTH, COUNT(*) AS NO_OF_BOXES_SHIPPED
FROM SALES
WHERE BOXES > 1000
GROUP BY DATE_FORMAT(SALEDATE,'%Y-%M') # DATE WILL EXTRACT LIKE THIS 2022-MARCH.......
ORDER BY MONTH DESC;

-- 4. Did we ship at least one box of ‘After Nines’ to ‘New Zealand’ on all the months?

-- 5. India or Australia? Who buys more chocolate boxes on a monthly basis?
SELECT DATE_FORMAT(S.SALEDATE, '%Y-%M') AS MONTH,
SUM(CASE WHEN GEO = 'India' THEN BOXES ELSE 0 END) AS India_Boxes,
SUM(CASE WHEN GEO = 'Australia' THEN BOXES ELSE 0 END) AS Australia_Boxes
FROM SALES S
JOIN GEO G ON S.GEOID = G.GEOID
WHERE GEO = 'INDIA' OR GEO = 'AUSTRALIA'
GROUP BY DATE_FORMAT(S.SALEDATE, '%Y-%M')
ORDER BY MONTH; #APRIL INDIA = 22514 AUSTRALIA = 35261 